/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.management.system;

import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
public class MenuCards extends javax.swing.JFrame {
Connection conn;
ResultSet rs;
PreparedStatement pst;
    /**
     * Creates new form MenuCards
     */
    public MenuCards() {
        super("Menu");
        initComponents();
        this.setLocationRelativeTo(null);
        conn=javaconnect.ConnecrDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLoginForm = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblUsername1 = new javax.swing.JLabel();
        lblUsername2 = new javax.swing.JLabel();
        lblUsername3 = new javax.swing.JLabel();
        lblUsername4 = new javax.swing.JLabel();
        lblUsername5 = new javax.swing.JLabel();
        lblUsername7 = new javax.swing.JLabel();
        cbMeal = new javax.swing.JComboBox<>();
        cbMealCount = new javax.swing.JComboBox<>();
        lblUsername8 = new javax.swing.JLabel();
        lblUsername9 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnCancel1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblTax = new javax.swing.JLabel();
        txtTax = new javax.swing.JTextField();
        lblSubTotal = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblLoginForm.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblLoginForm.setForeground(new java.awt.Color(240, 240, 240));
        lblLoginForm.setText("Menu Card");

        lblClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblClose.setForeground(new java.awt.Color(240, 240, 240));
        lblClose.setText("x");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        lblMinimize.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(240, 240, 240));
        lblMinimize.setText("-");
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoginForm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 704, Short.MAX_VALUE)
                .addComponent(lblMinimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblClose)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoginForm)
                    .addComponent(lblClose)
                    .addComponent(lblMinimize))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(240, 240, 240));
        lblUsername.setText("1.Set Menu - 1 ................................ 150/-");

        lblUsername1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUsername1.setForeground(new java.awt.Color(240, 240, 240));
        lblUsername1.setText("2.Set Menu - 2 ................................ 300/-");

        lblUsername2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUsername2.setForeground(new java.awt.Color(240, 240, 240));
        lblUsername2.setText("3.Set Menu - 3 ................................ 450/-");

        lblUsername3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUsername3.setForeground(new java.awt.Color(240, 240, 240));
        lblUsername3.setText("5.Pizza ............................................ 665/-");

        lblUsername4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUsername4.setForeground(new java.awt.Color(240, 240, 240));
        lblUsername4.setText("4.Pasta ........................................... 295/-");

        lblUsername5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUsername5.setForeground(new java.awt.Color(240, 240, 240));
        lblUsername5.setText("6.Burger ......................................... 255/-");

        lblUsername7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUsername7.setForeground(new java.awt.Color(240, 240, 240));
        lblUsername7.setText("7.Soup ............................................ 165/-");

        cbMeal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbMeal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Meal Item", "Set Menu-1", "Set Menu-2", "Set Menu-3", "Pasta", "Pizza", "Burger", "Soup" }));
        cbMeal.setPreferredSize(new java.awt.Dimension(6, 23));

        cbMealCount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbMealCount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Number of Meal", "1", "2", "3", "4" }));
        cbMealCount.setPreferredSize(new java.awt.Dimension(6, 23));

        lblUsername8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblUsername8.setForeground(new java.awt.Color(240, 240, 240));
        lblUsername8.setText("Which item do you want to order?");

        lblUsername9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblUsername9.setForeground(new java.awt.Color(240, 240, 240));
        lblUsername9.setText("How many item will you order?");

        btnCancel.setBackground(new java.awt.Color(242, 38, 19));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Back");
        btnCancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnCancel1.setBackground(new java.awt.Color(38, 166, 91));
        btnCancel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancel1.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel1.setText("Confirm");
        btnCancel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel1ActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(108, 122, 137));
        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "             Meal", "         Meal Count"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        lblTax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTax.setForeground(new java.awt.Color(240, 240, 240));
        lblTax.setText("Tax:");

        txtTax.setBackground(new java.awt.Color(108, 122, 137));
        txtTax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTax.setForeground(new java.awt.Color(228, 241, 254));
        txtTax.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTaxActionPerformed(evt);
            }
        });

        lblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSubTotal.setForeground(new java.awt.Color(240, 240, 240));
        lblSubTotal.setText("SubTotal:");

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(240, 240, 240));
        lblTotal.setText("Total:");

        txtSubTotal.setBackground(new java.awt.Color(108, 122, 137));
        txtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSubTotal.setForeground(new java.awt.Color(228, 241, 254));
        txtSubTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubTotalActionPerformed(evt);
            }
        });

        txtTotal.setBackground(new java.awt.Color(108, 122, 137));
        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(228, 241, 254));
        txtTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsername1)
                    .addComponent(lblUsername2)
                    .addComponent(lblUsername4)
                    .addComponent(lblUsername3)
                    .addComponent(lblUsername5)
                    .addComponent(lblUsername)
                    .addComponent(lblUsername7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lblUsername9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbMealCount, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(lblUsername8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)))
                .addGap(27, 27, 27)
                .addComponent(lblTax)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSubTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(432, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblUsername)
                .addGap(25, 25, 25)
                .addComponent(lblUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblUsername2)
                .addGap(18, 18, 18)
                .addComponent(lblUsername4)
                .addGap(18, 18, 18)
                .addComponent(lblUsername3)
                .addGap(18, 18, 18)
                .addComponent(lblUsername5)
                .addGap(18, 18, 18)
                .addComponent(lblUsername7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMealCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSubTotal)
                        .addComponent(lblTotal)
                        .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTax)
                        .addComponent(txtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(21, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(68, 68, 68)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        this.setState(jLogIn.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void btnCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel1ActionPerformed
        
        int SetMenu1 = 150;
        int SetMenu2 = 300;
        int SetMenu3 = 450;
        int Pasta = 295;
        int Pizza = 665;
        int Burger = 255;
        int Soup = 165;
        
        if(cbMeal.getSelectedItem().equals("Set Menu-1") && cbMealCount.getSelectedItem().equals("1"))
        {
            txtTotal.setText(Integer.toString(SetMenu1*1));
            txtTax.setText(Integer.toString(SetMenu1*1));
            txtSubTotal.setText(Integer.toString(SetMenu1*1));
            
            double q = Double.parseDouble (txtTax.getText());
            q=(q*10)/100;
            String tax = String.format(("BDT %.2f"), q);
            txtTax.setText(tax);
            
            double st = Double.parseDouble (txtSubTotal.getText());
            String subtotal = String.format(("BDT %.2f"), st);
            txtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble (txtTotal.getText());
            String total = String.format(("BDT %.2f"), tt+q);
            txtTotal.setText(total);
        }
        
        //===============================================================
        
        else if(cbMeal.getSelectedItem().equals("Set Menu-1") && cbMealCount.getSelectedItem().equals("2"))
        {
            txtTotal.setText(Integer.toString(SetMenu1*2));
            txtTax.setText(Integer.toString(SetMenu1*2));
            txtSubTotal.setText(Integer.toString(SetMenu1*2));
            
            double q = Double.parseDouble (txtTax.getText());
            q=(q*10)/100;
            String tax = String.format(("BDT %.2f"), q);
            txtTax.setText(tax);
            
            double st = Double.parseDouble (txtSubTotal.getText());
            String subtotal = String.format(("BDT %.2f"), st);
            txtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble (txtTotal.getText());
            String total = String.format(("BDT %.2f"), tt+q);
            txtTotal.setText(total);
        }
        
        //===============================================================
        
        else if(cbMeal.getSelectedItem().equals("Set Menu-1") && cbMealCount.getSelectedItem().equals("3"))
        {
            txtTotal.setText(Integer.toString(SetMenu1*3));
            txtTax.setText(Integer.toString(SetMenu1*3));
            txtSubTotal.setText(Integer.toString(SetMenu1*3));
            
            double q = Double.parseDouble (txtTax.getText());
            q=(q*10)/100;
            String tax = String.format(("BDT %.2f"), q);
            txtTax.setText(tax);
            
            double st = Double.parseDouble (txtSubTotal.getText());
            String subtotal = String.format(("BDT %.2f"), st);
            txtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble (txtTotal.getText());
            String total = String.format(("BDT %.2f"), tt+q);
            txtTotal.setText(total);
        }
        
        //===============================================================
        else if(cbMeal.getSelectedItem().equals("Set Menu-1") && cbMealCount.getSelectedItem().equals("4"))
        {
            txtTotal.setText(Integer.toString(SetMenu1*4));
            txtTax.setText(Integer.toString(SetMenu1*4));
            txtSubTotal.setText(Integer.toString(SetMenu1*4));
            
            double q = Double.parseDouble (txtTax.getText());
            q=(q*10)/100;
            String tax = String.format(("BDT %.2f"), q);
            txtTax.setText(tax);
            
            double st = Double.parseDouble (txtSubTotal.getText());
            String subtotal = String.format(("BDT %.2f"), st);
            txtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble (txtTotal.getText());
            String total = String.format(("BDT %.2f"), tt+q);
            txtTotal.setText(total);
        }
        
        //===============================================================
        else if(cbMeal.getSelectedItem().equals("Set Menu-2") && cbMealCount.getSelectedItem().equals("1"))
        {
            txtTotal.setText(Integer.toString(SetMenu2*1));
            txtTax.setText(Integer.toString(SetMenu2*1));
            txtSubTotal.setText(Integer.toString(SetMenu2*1));
            
            double q = Double.parseDouble (txtTax.getText());
            q=(q*10)/100;
            String tax = String.format(("BDT %.2f"), q);
            txtTax.setText(tax);
            
            double st = Double.parseDouble (txtSubTotal.getText());
            String subtotal = String.format(("BDT %.2f"), st);
            txtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble (txtTotal.getText());
            String total = String.format(("BDT %.2f"), tt+q);
            txtTotal.setText(total);
        }
        
        //===============================================================
        else if(cbMeal.getSelectedItem().equals("Set Menu-2") && cbMealCount.getSelectedItem().equals("2"))
        {
            txtTotal.setText(Integer.toString(SetMenu2*2));
            txtTax.setText(Integer.toString(SetMenu2*2));
            txtSubTotal.setText(Integer.toString(SetMenu2*2));
            
            double q = Double.parseDouble (txtTax.getText());
            q=(q*10)/100;
            String tax = String.format(("BDT %.2f"), q);
            txtTax.setText(tax);
            
            double st = Double.parseDouble (txtSubTotal.getText());
            String subtotal = String.format(("BDT %.2f"), st);
            txtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble (txtTotal.getText());
            String total = String.format(("BDT %.2f"), tt+q);
            txtTotal.setText(total);
        }
        
        //===============================================================
        else if(cbMeal.getSelectedItem().equals("Set Menu-2") && cbMealCount.getSelectedItem().equals("3"))
        {
            txtTotal.setText(Integer.toString(SetMenu2*3));
            txtTax.setText(Integer.toString(SetMenu2*3));
            txtSubTotal.setText(Integer.toString(SetMenu2*3));
            
            double q = Double.parseDouble (txtTax.getText());
            q=(q*10)/100;
            String tax = String.format(("BDT %.2f"), q);
            txtTax.setText(tax);
            
            double st = Double.parseDouble (txtSubTotal.getText());
            String subtotal = String.format(("BDT %.2f"), st);
            txtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble (txtTotal.getText());
            String total = String.format(("BDT %.2f"), tt+q);
            txtTotal.setText(total);
        }
        
        //===============================================================
        else if(cbMeal.getSelectedItem().equals("Set Menu-2") && cbMealCount.getSelectedItem().equals("4"))
        {
            txtTotal.setText(Integer.toString(SetMenu2*4));
            txtTax.setText(Integer.toString(SetMenu2*4));
            txtSubTotal.setText(Integer.toString(SetMenu2*4));
            
            double q = Double.parseDouble (txtTax.getText());
            q=(q*10)/100;
            String tax = String.format(("BDT %.2f"), q);
            txtTax.setText(tax);
            
            double st = Double.parseDouble (txtSubTotal.getText());
            String subtotal = String.format(("BDT %.2f"), st);
            txtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble (txtTotal.getText());
            String total = String.format(("BDT %.2f"), tt+q);
            txtTotal.setText(total);
        }
        
        //===============================================================
        else if(cbMeal.getSelectedItem().equals("Set Menu-3") && cbMealCount.getSelectedItem().equals("1"))
        {
            txtTotal.setText(Integer.toString(SetMenu3*1));
            txtTax.setText(Integer.toString(SetMenu3*1));
            txtSubTotal.setText(Integer.toString(SetMenu3*1));
            
            double q = Double.parseDouble (txtTax.getText());
            q=(q*10)/100;
            String tax = String.format(("BDT %.2f"), q);
            txtTax.setText(tax);
            
            double st = Double.parseDouble (txtSubTotal.getText());
            String subtotal = String.format(("BDT %.2f"), st);
            txtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble (txtTotal.getText());
            String total = String.format(("BDT %.2f"), tt+q);
            txtTotal.setText(total);
        }
        
        //===============================================================
        else if(cbMeal.getSelectedItem().equals("Set Menu-3") && cbMealCount.getSelectedItem().equals("2"))
        {
            txtTotal.setText(Integer.toString(SetMenu3*2));
            txtTax.setText(Integer.toString(SetMenu3*2));
            txtSubTotal.setText(Integer.toString(SetMenu3*2));
            
            double q = Double.parseDouble (txtTax.getText());
            q=(q*10)/100;
            String tax = String.format(("BDT %.2f"), q);
            txtTax.setText(tax);
            
            double st = Double.parseDouble (txtSubTotal.getText());
            String subtotal = String.format(("BDT %.2f"), st);
            txtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble (txtTotal.getText());
            String total = String.format(("BDT %.2f"), tt+q);
            txtTotal.setText(total);
        }
        
        //===============================================================
        else if(cbMeal.getSelectedItem().equals("Set Menu-3") && cbMealCount.getSelectedItem().equals("3"))
        {
            txtTotal.setText(Integer.toString(SetMenu3*3));
            txtTax.setText(Integer.toString(SetMenu3*3));
            txtSubTotal.setText(Integer.toString(SetMenu3*3));
            
            double q = Double.parseDouble (txtTax.getText());
            q=(q*10)/100;
            String tax = String.format(("BDT %.2f"), q);
            txtTax.setText(tax);
            
            double st = Double.parseDouble (txtSubTotal.getText());
            String subtotal = String.format(("BDT %.2f"), st);
            txtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble (txtTotal.getText());
            String total = String.format(("BDT %.2f"), tt+q);
            txtTotal.setText(total);
        }
        
        //===============================================================
        else if(cbMeal.getSelectedItem().equals("Set Menu-3") && cbMealCount.getSelectedItem().equals("4"))
        {
            txtTotal.setText(Integer.toString(SetMenu3*4));
            txtTax.setText(Integer.toString(SetMenu3*4));
            txtSubTotal.setText(Integer.toString(SetMenu3*4));
            
            double q = Double.parseDouble (txtTax.getText());
            q=(q*10)/100;
            String tax = String.format(("BDT %.2f"), q);
            txtTax.setText(tax);
            
            double st = Double.parseDouble (txtSubTotal.getText());
            String subtotal = String.format(("BDT %.2f"), st);
            txtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble (txtTotal.getText());
            String total = String.format(("BDT %.2f"), tt+q);
            txtTotal.setText(total);
        }
        
        //===============================================================
        else if(cbMeal.getSelectedItem().equals("Pasta") && cbMealCount.getSelectedItem().equals("1"))
        {
            txtTotal.setText(Integer.toString(Pasta*1));
            txtTax.setText(Integer.toString(Pasta*1));
            txtSubTotal.setText(Integer.toString(Pasta*1));
            
            double q = Double.parseDouble (txtTax.getText());
            q=(q*10)/100;
            String tax = String.format(("BDT %.2f"), q);
            txtTax.setText(tax);
            
            double st = Double.parseDouble (txtSubTotal.getText());
            String subtotal = String.format(("BDT %.2f"), st);
            txtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble (txtTotal.getText());
            String total = String.format(("BDT %.2f"), tt+q);
            txtTotal.setText(total);
        }
        
        //===============================================================
        else if(cbMeal.getSelectedItem().equals("Pasta") && cbMealCount.getSelectedItem().equals("2"))
        {
            txtTotal.setText(Integer.toString(Pasta*2));
            txtTax.setText(Integer.toString(Pasta*2));
            txtSubTotal.setText(Integer.toString(Pasta*2));
            
            double q = Double.parseDouble (txtTax.getText());
            q=(q*10)/100;
            String tax = String.format(("BDT %.2f"), q);
            txtTax.setText(tax);
            
            double st = Double.parseDouble (txtSubTotal.getText());
            String subtotal = String.format(("BDT %.2f"), st);
            txtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble (txtTotal.getText());
            String total = String.format(("BDT %.2f"), tt+q);
            txtTotal.setText(total);
        }
        
        //===============================================================
        else if(cbMeal.getSelectedItem().equals("Pasta") && cbMealCount.getSelectedItem().equals("3"))
        {
            txtTotal.setText(Integer.toString(Pasta*3));
            txtTax.setText(Integer.toString(Pasta*3));
            txtSubTotal.setText(Integer.toString(Pasta*3));
            
            double q = Double.parseDouble (txtTax.getText());
            q=(q*10)/100;
            String tax = String.format(("BDT %.2f"), q);
            txtTax.setText(tax);
            
            double st = Double.parseDouble (txtSubTotal.getText());
            String subtotal = String.format(("BDT %.2f"), st);
            txtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble (txtTotal.getText());
            String total = String.format(("BDT %.2f"), tt+q);
            txtTotal.setText(total);
        }
        
        //===============================================================
        else if(cbMeal.getSelectedItem().equals("Pasta") && cbMealCount.getSelectedItem().equals("4"))
        {
            txtTotal.setText(Integer.toString(Pasta*4));
            txtTax.setText(Integer.toString(Pasta*4));
            txtSubTotal.setText(Integer.toString(Pasta*4));
            
            double q = Double.parseDouble (txtTax.getText());
            q=(q*10)/100;
            String tax = String.format(("BDT %.2f"), q);
            txtTax.setText(tax);
            
            double st = Double.parseDouble (txtSubTotal.getText());
            String subtotal = String.format(("BDT %.2f"), st);
            txtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble (txtTotal.getText());
            String total = String.format(("BDT %.2f"), tt+q);
            txtTotal.setText(total);
        }
        
        //===============================================================
        else if(cbMeal.getSelectedItem().equals("Pizza") && cbMealCount.getSelectedItem().equals("1"))
        {
            txtTotal.setText(Integer.toString(Pizza*1));
            txtTax.setText(Integer.toString(Pizza*1));
            txtSubTotal.setText(Integer.toString(Pizza*1));
            
            double q = Double.parseDouble (txtTax.getText());
            q=(q*10)/100;
            String tax = String.format(("BDT %.2f"), q);
            txtTax.setText(tax);
            
            double st = Double.parseDouble (txtSubTotal.getText());
            String subtotal = String.format(("BDT %.2f"), st);
            txtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble (txtTotal.getText());
            String total = String.format(("BDT %.2f"), tt+q);
            txtTotal.setText(total);
        }
        
        //===============================================================
        else if(cbMeal.getSelectedItem().equals("Pizza") && cbMealCount.getSelectedItem().equals("2"))
        {
            txtTotal.setText(Integer.toString(Pizza*2));
            txtTax.setText(Integer.toString(Pizza*2));
            txtSubTotal.setText(Integer.toString(Pizza*2));
            
            double q = Double.parseDouble (txtTax.getText());
            q=(q*10)/100;
            String tax = String.format(("BDT %.2f"), q);
            txtTax.setText(tax);
            
            double st = Double.parseDouble (txtSubTotal.getText());
            String subtotal = String.format(("BDT %.2f"), st);
            txtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble (txtTotal.getText());
            String total = String.format(("BDT %.2f"), tt+q);
            txtTotal.setText(total);
        }
        
        //===============================================================
        else if(cbMeal.getSelectedItem().equals("Pizza") && cbMealCount.getSelectedItem().equals("3"))
        {
            txtTotal.setText(Integer.toString(Pizza*3));
            txtTax.setText(Integer.toString(Pizza*3));
            txtSubTotal.setText(Integer.toString(Pizza*3));
            
            double q = Double.parseDouble (txtTax.getText());
            q=(q*10)/100;
            String tax = String.format(("BDT %.2f"), q);
            txtTax.setText(tax);
            
            double st = Double.parseDouble (txtSubTotal.getText());
            String subtotal = String.format(("BDT %.2f"), st);
            txtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble (txtTotal.getText());
            String total = String.format(("BDT %.2f"), tt+q);
            txtTotal.setText(total);
        }
        
        //===============================================================
        else if(cbMeal.getSelectedItem().equals("Pizza") && cbMealCount.getSelectedItem().equals("4"))
        {
            txtTotal.setText(Integer.toString(Pizza*4));
            txtTax.setText(Integer.toString(Pizza*4));
            txtSubTotal.setText(Integer.toString(Pizza*4));
            
            double q = Double.parseDouble (txtTax.getText());
            q=(q*10)/100;
            String tax = String.format(("BDT %.2f"), q);
            txtTax.setText(tax);
            
            double st = Double.parseDouble (txtSubTotal.getText());
            String subtotal = String.format(("BDT %.2f"), st);
            txtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble (txtTotal.getText());
            String total = String.format(("BDT %.2f"), tt+q);
            txtTotal.setText(total);
        }
        
        //===============================================================
        else if(cbMeal.getSelectedItem().equals("Burger") && cbMealCount.getSelectedItem().equals("2"))
        {
            txtTotal.setText(Integer.toString(Burger*2));
            txtTax.setText(Integer.toString(Burger*2));
            txtSubTotal.setText(Integer.toString(Burger*2));
            
            double q = Double.parseDouble (txtTax.getText());
            q=(q*10)/100;
            String tax = String.format(("BDT %.2f"), q);
            txtTax.setText(tax);
            
            double st = Double.parseDouble (txtSubTotal.getText());
            String subtotal = String.format(("BDT %.2f"), st);
            txtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble (txtTotal.getText());
            String total = String.format(("BDT %.2f"), tt+q);
            txtTotal.setText(total);
        }
        
        //===============================================================
        else if(cbMeal.getSelectedItem().equals("Burger") && cbMealCount.getSelectedItem().equals("1"))
        {
            txtTotal.setText(Integer.toString(Burger*1));
            txtTax.setText(Integer.toString(Burger*1));
            txtSubTotal.setText(Integer.toString(Burger*1));
            
            double q = Double.parseDouble (txtTax.getText());
            q=(q*10)/100;
            String tax = String.format(("BDT %.2f"), q);
            txtTax.setText(tax);
            
            double st = Double.parseDouble (txtSubTotal.getText());
            String subtotal = String.format(("BDT %.2f"), st);
            txtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble (txtTotal.getText());
            String total = String.format(("BDT %.2f"), tt+q);
            txtTotal.setText(total);
        }
        
        //===============================================================
        else if(cbMeal.getSelectedItem().equals("Burger") && cbMealCount.getSelectedItem().equals("3"))
        {
            txtTotal.setText(Integer.toString(Burger*3));
            txtTax.setText(Integer.toString(Burger*3));
            txtSubTotal.setText(Integer.toString(Burger*3));
            
            double q = Double.parseDouble (txtTax.getText());
            q=(q*10)/100;
            String tax = String.format(("BDT %.2f"), q);
            txtTax.setText(tax);
            
            double st = Double.parseDouble (txtSubTotal.getText());
            String subtotal = String.format(("BDT %.2f"), st);
            txtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble (txtTotal.getText());
            String total = String.format(("BDT %.2f"), tt+q);
            txtTotal.setText(total);
        }
        
        //===============================================================
        else if(cbMeal.getSelectedItem().equals("Burger") && cbMealCount.getSelectedItem().equals("4"))
        {
            txtTotal.setText(Integer.toString(Burger*4));
            txtTax.setText(Integer.toString(Burger*4));
            txtSubTotal.setText(Integer.toString(Burger*4));
            
            double q = Double.parseDouble (txtTax.getText());
            q=(q*10)/100;
            String tax = String.format(("BDT %.2f"), q);
            txtTax.setText(tax);
            
            double st = Double.parseDouble (txtSubTotal.getText());
            String subtotal = String.format(("BDT %.2f"), st);
            txtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble (txtTotal.getText());
            String total = String.format(("BDT %.2f"), tt+q);
            txtTotal.setText(total);
        }
        
        //===============================================================
        else if(cbMeal.getSelectedItem().equals("Soup") && cbMealCount.getSelectedItem().equals("1"))
        {
            txtTotal.setText(Integer.toString(Soup*1));
            txtTax.setText(Integer.toString(Soup*1));
            txtSubTotal.setText(Integer.toString(Soup*1));
            
            double q = Double.parseDouble (txtTax.getText());
            q=(q*10)/100;
            String tax = String.format(("BDT %.2f"), q);
            txtTax.setText(tax);
            
            double st = Double.parseDouble (txtSubTotal.getText());
            String subtotal = String.format(("BDT %.2f"), st);
            txtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble (txtTotal.getText());
            String total = String.format(("BDT %.2f"), tt+q);
            txtTotal.setText(total);
        }
        
        //===============================================================
         else if(cbMeal.getSelectedItem().equals("Soup") && cbMealCount.getSelectedItem().equals("2"))
        {
            txtTotal.setText(Integer.toString(Soup*2));
            txtTax.setText(Integer.toString(Soup*2));
            txtSubTotal.setText(Integer.toString(Soup*2));
            
            double q = Double.parseDouble (txtTax.getText());
            q=(q*10)/100;
            String tax = String.format(("BDT %.2f"), q);
            txtTax.setText(tax);
            
            double st = Double.parseDouble (txtSubTotal.getText());
            String subtotal = String.format(("BDT %.2f"), st);
            txtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble (txtTotal.getText());
            String total = String.format(("BDT %.2f"), tt+q);
            txtTotal.setText(total);
        }
        
        //===============================================================
         else if(cbMeal.getSelectedItem().equals("Soup") && cbMealCount.getSelectedItem().equals("3"))
        {
            txtTotal.setText(Integer.toString(Soup*3));
            txtTax.setText(Integer.toString(Soup*3));
            txtSubTotal.setText(Integer.toString(Soup*3));
            
            double q = Double.parseDouble (txtTax.getText());
            q=(q*10)/100;
            String tax = String.format(("BDT %.2f"), q);
            txtTax.setText(tax);
            
            double st = Double.parseDouble (txtSubTotal.getText());
            String subtotal = String.format(("BDT %.2f"), st);
            txtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble (txtTotal.getText());
            String total = String.format(("BDT %.2f"), tt+q);
            txtTotal.setText(total);
        }
        
        //===============================================================
         else if(cbMeal.getSelectedItem().equals("Soup") && cbMealCount.getSelectedItem().equals("4"))
        {
            txtTotal.setText(Integer.toString(Soup*4));
            txtTax.setText(Integer.toString(Soup*4));
            txtSubTotal.setText(Integer.toString(Soup*4));
            
            double q = Double.parseDouble (txtTax.getText());
            q=(q*10)/100;
            String tax = String.format(("BDT %.2f"), q);
            txtTax.setText(tax);
            
            double st = Double.parseDouble (txtSubTotal.getText());
            String subtotal = String.format(("BDT %.2f"), st);
            txtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble (txtTotal.getText());
            String total = String.format(("BDT %.2f"), tt+q);
            txtTotal.setText(total);
        }
        
        //===============================================================
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]
        {
        cbMeal.getSelectedItem(),
        cbMealCount.getSelectedItem(),
        });
    }//GEN-LAST:event_btnCancel1ActionPerformed

    private void txtTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTaxActionPerformed

    private void txtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubTotalActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
            WindowEvent winCloseing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
            Guest g = new Guest();
            g.setVisible(true);
            g.pack();
            g.setLocationRelativeTo(null);
            g.setDefaultCloseOperation(MenuCards.EXIT_ON_CLOSE);
            this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCards().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancel1;
    private javax.swing.JComboBox<String> cbMeal;
    private javax.swing.JComboBox<String> cbMealCount;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblLoginForm;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTax;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JLabel lblUsername2;
    private javax.swing.JLabel lblUsername3;
    private javax.swing.JLabel lblUsername4;
    private javax.swing.JLabel lblUsername5;
    private javax.swing.JLabel lblUsername7;
    private javax.swing.JLabel lblUsername8;
    private javax.swing.JLabel lblUsername9;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTax;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
